# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

sudo: false

language: php

env:
  global:
    - COMPOSER_ROOT_VERSION=4.0.x-dev
    - SS_ENVIRONMENT_TYPE="dev"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DB=MYSQL
    - php: 5.6
      env:
        - DB=PGSQL
    - php: 7.0
      env:
        - DB=MYSQL
    - php: 7.0
      env:
        - DB=PGSQL
    - php: 7.1
      env:
        - DB=MYSQL
    - php: 7.1
      env:
        - DB=PGSQL
  allow_failures:

before_script:
  - composer self-update || true
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit jsontext/tests

branches:
  only: 
    - master
